### ISSUE TITLE
[syncfusion_flutter_charts] LinearSeries exception

### ISSUE THREAD

**Issue by AndreHaueisen** [syncfusion/flutter-examples#183]
When a linear series has only one of its points different than null, this exception is thrown:
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The getter 'x' was called on null.
Receiver: null
Tried calling: x

The relevant error-causing widget was:
  SfCartesianChart
  file:///C:/Users/andre/Desktop/flutter_apps/mindid/lib/charts/bar_line_chart.dart:17:12

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SplineSegment.calculateSegmentPoints (package:syncfusion_flutter_charts/src/chart/chart_segment/spline_segment.dart:100:48)
#2      SplineSeriesRenderer.addSegment (package:syncfusion_flutter_charts/src/chart/chart_series/spline_series.dart:169:15)
#3      _SplineChartPainter.paint (package:syncfusion_flutter_charts/src/chart/series_painter/spline_painter.dart:74:30)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:533:13)
#5      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:574:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#10     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#11     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#12     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:7)
#14     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#15     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#16     RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#20     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2061:11)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#24     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2061:11)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#27     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:316:15)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#33     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#34     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#35     RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#38     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#41     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
#42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#44     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:316:15)
#45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#47     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#48     RenderFlex.paint (package:flutter/src/rendering/flex.dart:969:7)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#51     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
#52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#54     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#57     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#58     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2061:11)
#59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#61     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
#62     _ChartContainerBox.paint (package:syncfusion_flutter_charts/src/common/common.dart:41:11)
#63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#65     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#66     RenderFlex.paint (package:flutter/src/rendering/flex.dart:969:7)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#69     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
#70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#72     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#73     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2061:11)
#74     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#75     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#76     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#77     RenderFlex.paint (package:flutter/src/rendering/flex.dart:969:7)
#78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#79     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#80     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#81     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:406:5)
#82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#83     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#84     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#85     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:533:11)
#86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#89     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:393:12)
#90     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1821:15)
#91     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#92     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#93     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:916:17)
#94     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#95     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#96     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#97     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2265:15)
#98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#100    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:916:17)
#101    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#102    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#103    _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7253:15)
#104    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#105    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#106    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:916:17)
#107    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#108    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#109    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#110    RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2265:15)
#111    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#112    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#113    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:916:17)
#114    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#115    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#116    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#117    RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#118    RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#119    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#120    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#121    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
#122    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#123    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#124    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#125    RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#126    RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#127    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#128    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#129    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#130    _RenderInkFeatures.paint (package:flutter/src/material/material.dart:533:11)
#131    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#132    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#133    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#134    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:393:12)
#135    RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1821:15)
#136    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#137    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#138    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#139    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#140    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#141    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#142    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#143    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#144    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#145    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:982:29)
#146    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:406:19)
#147    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#148    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#149    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#150    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#151    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#155    _invoke (dart:ui/hooks.dart:253:10)
#156    _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)

The following RenderObject was being processed when the exception was fired: RenderCustomPaint#48d01 relayoutBoundary=up2:
  creator: CustomPaint ← RepaintBoundary ← Container ← Stack ← Container ← DecoratedBox ← Container ←
    DecoratedBox ← Container ← LayoutBuilder ← _ContainerArea ← ConstrainedBox ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=340.7, 0.0<=h<=288.3)
  size: Size(0.0, 0.0)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The getter 'x' was called on null.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The getter 'x' was called on null.
Receiver: null
Tried calling: x
```

This is the code

```
  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      plotAreaBorderWidth: 0.0,
      borderWidth: 0.0,
      legend: Legend(
        position: LegendPosition.bottom,
        isVisible: true,
        toggleSeriesVisibility: true,
        overflowMode: LegendItemOverflowMode.scroll,
      ),
      primaryXAxis: CategoryAxis(
        tickPosition: TickPosition.inside,
        axisLine: AxisLine(width: 0),
        majorGridLines: MajorGridLines(width: 0.0),
        majorTickLines: MajorTickLines(width: 0.0),
      ),
      primaryYAxis: NumericAxis(
        title: AxisTitle(
          text: 'Title',
          alignment: ChartAlignment.center,
        ),
        opposedPosition: true,
        maximum: 18,
        axisLine: AxisLine(width: 0),
        majorTickLines: MajorTickLines(width: 0),
        majorGridLines: MajorGridLines(color: Colors.lightBlueAccent),
      ),
      series: <CartesianSeries>[
        _buildLineSeries(),
      ],
    );
  }
```
```
 ColumnSeries<CheckIn, String> _buildColumnSeries() {
    return ColumnSeries<CheckIn, String>(
      color: AppTheme.accentRed,
      width: 0.7,
      borderRadius: BorderRadius.all(Radius.circular(2)),
      trackBorderWidth: 0,
      isVisibleInLegend: false,
      dataLabelSettings: DataLabelSettings(
        isVisible: true,
        builder: _buildLabel,
      ),
      dataSource: checkIns,
      xValueMapper: (CheckIn checkIn, _) => DateFormat(DateFormat.ABBR_WEEKDAY).format(checkIn.dateWithoutTime),
      yValueMapper: (CheckIn checkIn, _) => checkIn.sleepAnswers?.answer0?.answer?.inHours,
    );
  }
```

The exception goes away if I add another data point != null.
I'm using version 18.2.48

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AndreHaueisen,

Greetings from Syncfusion. We have analyzed your scenario with the provided code snippet and information and we are able to replicate the reported issue regarding throwing of exception when one of the series data points is different than null and this issue occurred only when using spline series at our end. We will consider this a bug and we will include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by 25th August 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AndreHaueisen,

Thanks for your patience. The reported issue regarding throwing of exception when one of the series data points is different than null when using spline series is now fixed and rolled out in our weekly patch release. To overcome the reported issue, kindly upgrade the chart widget package version to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.55

Regards,
Sriram Kiran

**Comment by AndreHaueisen** [comment]
All good now. Thank you.
