### ISSUE TITLE
[Calendar] - exception when calendar view is CalendarView.week and there are many appointments for specific time slot

### ISSUE THREAD

**Issue by angel1st** [syncfusion/flutter-examples#186]
Hi there,
This is the exception I have got:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following ArgumentError was thrown during paint():
Invalid argument(s): 0.0

The relevant error-causing widget was:
  SfCalendar
  file:///D:/Working/plant_care_reminder/lib/presentation/widgets/history_calendar_widget.dart:142:26

When the exception was thrown, this was the stack:
#0      double.clamp (dart:core-patch/double.dart:183:7)
#1      TextPainter.layout (package:flutter/src/painting/text_painter.dart:571:49)
#2      _AppointmentPainter._drawDayAppointments (package:syncfusion_flutter_calendar/src/calendar/appointment_layout/appointment_layout.dart:477:15)
#3      _AppointmentPainter.paint (package:syncfusion_flutter_calendar/src/calendar/appointment_layout/appointment_layout.dart:72:7)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:533:13)
#5      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:579:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#10     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#11     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#12     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:7)
#14     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#15     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#16     RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#21     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#22     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#23     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:7)
#25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#28     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:649:17)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#31     RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:279:15)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#34     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:606:17)
#35     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:393:12)
#36     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:449:7)
#37     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:597:15)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#39     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#40     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#41     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:7)
#43     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#52     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#55     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#56     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#57     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#58     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#61     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#63     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#64     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#65     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:7)
#67     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#68     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:577:11)
#69     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#70     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#71     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#73     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#74     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#75     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#76     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:7)
#77     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#78     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#79     RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#82     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#84     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#85     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#89     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#90     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#91     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#92     RenderWrap.paint (package:flutter/src/rendering/wrap.dart:775:7)
#93     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#95     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#96     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#97     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#98     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#99     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#100    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#101    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#102    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#103    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#104    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#105    RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#106    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:393:12)
#107    PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:449:7)
#108    RenderStack.paint (package:flutter/src/rendering/stack.dart:614:15)
#109    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#110    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#111    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#112    RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#113    RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#114    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#115    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#116    _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7253:15)
#117    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#118    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#119    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#120    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#121    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#122    _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:316:15)
#123    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#124    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#125    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#126    RenderStack.paintStack (package:flutter/src/rendering/stack.dart:608:5)
#127    RenderStack.paint (package:flutter/src/rendering/stack.dart:616:7)
#128    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#129    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#130    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#131    RenderFlex.paint (package:flutter/src/rendering/flex.dart:969:7)
#132    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#133    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#134    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
#135    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#136    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#137    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2525:15)
#138    RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:406:5)
#139    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#140    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#141    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#142    _RenderInkFeatures.paint (package:flutter/src/material/material.dart:533:11)
#143    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#144    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#145    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#146    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:393:12)
#147    RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1821:15)
#148    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#149    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#150    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
#151    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#152    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#153    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#154    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:982:29)
#155    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:406:19)
#156    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#157    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#158    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#159    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#160    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#164    _invoke (dart:ui/hooks.dart:253:10)
#165    _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)

The following RenderObject was being processed when the exception was fired: RenderCustomPaint#4cfb5 relayoutBoundary=up7:
  creator: CustomPaint ← RepaintBoundary ← Stack ← RepaintBoundary ← IndexedSemantics ←
    NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ←
    SliverList ← SliverPadding ← Viewport ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  semantic boundary
  size: Size(411.4, 960.0)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11713): Transition { currentState: HistoryCalendarStateSet, event: HistoryCalendarEventSetDateRange, nextState: HistoryCalendarStateIsLoading }

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following ArgumentError was thrown during paint():
Invalid argument(s): 0.0

The relevant error-causing widget was: 
  SfCalendar file:///D:/Working/plant_care_reminder/lib/presentation/widgets/history_calendar_widget.dart:142:26
When the exception was thrown, this was the stack: 
#0      double.clamp (dart:core-patch/double.dart:183:7)
#1      TextPainter.layout (package:flutter/src/painting/text_painter.dart:571:49)
#2      _AppointmentPainter._drawDayAppointments (package:syncfusion_flutter_calendar/src/calendar/appointment_layout/appointment_layout.dart:477:15)
#3      _AppointmentPainter.paint (package:syncfusion_flutter_calendar/src/calendar/appointment_layout/appointment_layout.dart:72:7)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:533:13)
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#4cfb5 relayoutBoundary=up7
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  semantic boundary
...  size: Size(411.4, 960.0)
RenderObject: RenderCustomPaint#4cfb5 relayoutBoundary=up7
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  semantic boundary
  size: Size(411.4, 960.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Invalid argument(s): 0.0

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Invalid argument(s): 0.0
The relevant error-causing widget was: 
  SfCalendar file:///D:/Working/plant_care_reminder/lib/presentation/widgets/history_calendar_widget.dart:142:26
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11713): Transition { currentState: HistoryCalendarStateIsLoading, event: HistoryCalendarEventSetDateRange, nextState: HistoryCalendarStateSet }
I/flutter (11713): Transition { currentState: HistoryCalendarStateSet, event: HistoryCalendarEventSelectDate, nextState: HistoryCalendarStateIsLoading }
I/flutter (11713): Transition { currentState: HistoryCalendarStateIsLoading, event: HistoryCalendarEventSelectDate, nextState: HistoryCalendarStateSet }

Another exception was thrown: Invalid argument(s): 0.0

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following ArgumentError was thrown during paint():
Invalid argument(s): 0.0

The relevant error-causing widget was: 
  SfCalendar file:///D:/Working/plant_care_reminder/lib/presentation/widgets/history_calendar_widget.dart:142:26
When the exception was thrown, this was the stack: 
#0      double.clamp (dart:core-patch/double.dart:183:7)
#1      TextPainter.layout (package:flutter/src/painting/text_painter.dart:571:49)
#2      _AppointmentPainter._drawDayAppointments (package:syncfusion_flutter_calendar/src/calendar/appointment_layout/appointment_layout.dart:477:15)
#3      _AppointmentPainter.paint (package:syncfusion_flutter_calendar/src/calendar/appointment_layout/appointment_layout.dart:72:7)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:533:13)
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#4cfb5 relayoutBoundary=up7
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  semantic boundary
...  size: Size(411.4, 960.0)
RenderObject: RenderCustomPaint#4cfb5 relayoutBoundary=up7
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  semantic boundary
  size: Size(411.4, 960.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

Please note it happens only in case these are actual appointments made within a small time span (i.e. not recurrent ones).

**Comment by Indumathi1195R** [comment]
Hi @angel1st ,

Currently, we are validating the issue. We will validate and let you know the details on or before August 21, 2020. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @angel1st ,

We have already found and fixed the mentioned issue “**Exception occurred when setting more appointments in same timeslots**” and we will include the issue fix in our upcoming Weekly Nuget release package, which is expected to rollout by August 25, 2020. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @angel1st ,

Thank you for your patience.

We have included the mentioned issue fix for “**Exception occurred when setting more appointments in same timeslots**” in our latest weekly package. Kindly update the Flutter calendar package to the latest version (18.2.55). Also please find the changelog for the same

**Link:** https://pub.dev/packages/syncfusion_flutter_calendar#-changelog-tab-

Regards,
Indumathi R

**Comment by angel1st** [comment]
Thanks, @Indumathi1195R - I can confirm the issue has been resolved. I am closing the ticket.
