### ISSUE TITLE
When I keep pin zooming, it crashes when I reach the boundary.

### ISSUE THREAD

**Issue by chongbo2013** [syncfusion/flutter-examples#238]
When I keep pin zooming, it crashes when I reach the boundary.
═══════ Exception caught by gesture library ═══════════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following _TypeError was thrown while dispatching a pointer event:
type 'int' is not a subtype of type 'double'

When the exception was thrown, this was the stack: 
#0      ZoomPanBehaviorRenderer._performMouseWheelZooming (package:syncfusion_flutter_charts/src/chart/user_interaction/zooming_panning.dart:807:24)
#1      _ContainerArea._performPointerSignal (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2529:14)
#2      _ContainerArea._getListener.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2956:13)
#3      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2730:31)
#4      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/99628051-5a065400-2a70-11eb-8ed7-dbcd3501cf5d.png)
When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart:219:36)
#1      double.floor (dart:core-patch/double.dart:183:34)
#2      DateTimeAxisRenderer._alignRangeStart (package:syncfusion_flutter_charts/src/chart/axis/datetime_axis.dart:405:43)
#3      DateTimeAxisRenderer.generateVisibleLabels (package:syncfusion_flutter_charts/src/chart/axis/datetime_axis.dart:875:16)
#4      DateTimeAxisRenderer._calculateRangeAndInterval (package:syncfusion_flutter_charts/src/chart/axis/datetime_axis.dart:307:9)

![Uploading image.png…]()
