### ISSUE TITLE
_CastError: Null check operator used on a null value

### ISSUE THREAD

**Issue by psrcek** [syncfusion/flutter-examples#342]
This happens sometimes with sound null safety enabled.

```
_CastError: Null check operator used on a null value
  File "calendar_view.dart", line 4346, in _CalendarViewState._handleTouchOnMonthView
  File "calendar_view.dart", line 4288, in _CalendarViewState._handleOnTapForMonth
  File "calendar_view.dart", line 3327, in _CalendarViewState._getMonthView.<fn>
  File "tap.dart", line 605, in TapGestureRecognizer.handleTapUp.<fn>
  File "recognizer.dart", line 182, in GestureRecognizer.invokeCallback
  File "tap.dart", line 605, in TapGestureRecognizer.handleTapUp
  File "tap.dart", line 296, in BaseTapGestureRecognizer._checkUp
  File "tap.dart", line 267, in BaseTapGestureRecognizer.acceptGesture
  File "arena.dart", line 157, in GestureArenaManager.sweep
  File "binding.dart", line 385, in GestureBinding.handleEvent
  File "binding.dart", line 361, in GestureBinding.dispatchEvent
  File "binding.dart", line 278, in RendererBinding.dispatchEvent
  File "binding.dart", line 316, in GestureBinding._handlePointerEventImmediately
  File "binding.dart", line 280, in GestureBinding.handlePointerEvent
  File "binding.dart", line 238, in GestureBinding._flushPointerEventQueue
  File "binding.dart", line 221, in GestureBinding._handlePointerDataPacket
  File "zone.dart", line 1370, in _rootRunUnary
  File "zone.dart", line 1265, in _CustomZone.runUnary
  File "zone.dart", line 1170, in _CustomZone.runUnaryGuarded
  File "hooks.dart", line 180, in _invoke1
  File "platform_dispatcher.dart", line 276, in PlatformDispatcher._dispatchPointerDataPacket
  File "hooks.dart", line 96, in _dispatchPointerDataPacket
```

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**Cast error occurred while null safety enabled in the Flutter Calendar**” in the simple sample and it is working fine as expected from our end. We have ensured with all views with tapped actions and unable to reproduce the issue. We have prepared a simple sample for the same. Please find the sample from the following link.

**Sample link:** 
[flutter_calendarnullsafety.zip](https://github.com/syncfusion/flutter-examples/files/6438990/flutter_calendarnullsafety.zip)

If possible, can you please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us back with the following details.

•	Issue reproducing scenario
•	Replication video
•	Code snippets related to SfCalendar and onTap callback
•	Tested device

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @psrcek,

Thank you for the update.

Based on the shared code snippet, we have checked the mentioned issue and we are unable to reproduce the error from our end and we suspect your requirement is “**To show the appointments in custom agenda view using onTap callback**”. We have a KB document for the same. Please find the KB document from the following link.

**KB link:**
https://www.syncfusion.com/kb/11016/how-to-show-a-custom-agenda-view-in-the-flutter-calendar

If this is not your requirement, can you please share more details about your requirement and the mentioned error details clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by brightseagit** [comment]
I'm also facing this issue. 
So, I'm posting the sample code through which you can regenerate the issue (copy the whole code to main.dart): 
```
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'dart:io';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  PlatformFile selectedFile;

  void onTapAction() async {
    FilePickerResult result = await FilePicker.platform.pickFiles();
    if (result != null) {
      //Selecting file and getting path using file picker
      selectedFile = result.files.first;
      print(selectedFile.path);

      //Loads an existing PDF document from selected file path
      final PdfDocument document =
          PdfDocument(inputBytes: File(selectedFile.path).readAsBytesSync());

      //Loads the existing PDF page
      PdfPage page = document.pages[0];

      //Creates a rectangle annotation
      PdfRectangleAnnotation rectangleAnnotation = PdfRectangleAnnotation(
          Rect.fromLTWH(40, 70, 80, 80), 'Rectangle Annotation',
          author: 'Syncfusion',
          color: PdfColor(255, 0, 0),
          modifiedDate: DateTime.now());

      //Adds the annotation to the loaded page
      page.annotations.add(rectangleAnnotation);

      //Saves the document
      List<int> bytes = document.save();
      File('output.pdf').writeAsBytes(document.save());

      //Disposes the document
      document.dispose();

      Future<void> saveAndLaunchFile(List<int> bytes, String fileName) async {
        final path = (await getExternalStorageDirectory()).path;
        final file = File('$path/$fileName');
        await file.writeAsBytes(bytes, flush: true);
        OpenFile.open('$path/$fileName');
      }

      saveAndLaunchFile(bytes, 'Output.pdf');
    } else {
      // User canceled the picker
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextButton(
        onPressed: onTapAction,
        child: Center(child: Text('Select File')),
      ),
    );
  }
}
```

Also, add these plugins in pubsec.yaml:
```
  file_picker: ^3.0.1
  syncfusion_flutter_pdf: ^19.1.63-beta
  path_provider: ^2.0.1
  open_file: ^3.2.1
```

Full Error:
```
E/flutter (11401): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
E/flutter (11401): #0      _PdfString.decrypt (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_string.dart:357:33)
E/flutter (11401): #1      _PdfCrossTable._decrypt (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:876:17)
E/flutter (11401): #2      _PdfCrossTable._decrypt.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:847:13)
E/flutter (11401): #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (11401): #4      _PdfCrossTable._decrypt (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:846:23)
E/flutter (11401): #5      _PdfCrossTable._decrypt (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:869:11)
E/flutter (11401): #6      _PdfCrossTable._decrypt.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:847:13)
E/flutter (11401): #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (11401): #8      _PdfCrossTable._decrypt (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:846:23)
E/flutter (11401): #9      _PdfCrossTable._getObject (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:619:9)
E/flutter (11401): #10     _PdfReferenceHolder.index (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_reference_holder.dart:53:18)
E/flutter (11401): #11     _PdfReferenceHolder._obtainObject (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_reference_holder.dart:131:11)
E/flutter (11401): #12     _PdfReferenceHolder.object (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_reference_holder.dart:40:17)
E/flutter (11401): #13     _PdfCrossTable._dereference (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:558:21)
E/flutter (11401): #14     _PdfCrossTable.documentCatalog (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:69:11)
E/flutter (11401): #15     PdfDocument._getCatalogValue (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/pdf_document.dart:786:52)
E/flutter (11401): #16     PdfDocument._initialize (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/pdf_document.dart:613:35)
E/flutter (11401): #17     new PdfDocument (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/pdf_document.dart:35:5)
E/flutter (11401): #18     _MyHomePageState.onTapAction (package:testsample/main.dart:47:11)
E/flutter (11401): <asynchronous suspension>
E/flutter (11401): 
```
Thanks

**Comment by brightseagit** [comment]
Hey, figured out that in my case the error occurred because the file had restricted permissions.

**Comment by psrcek** [comment]
Also you're not using the calendar.

**Comment by Indumathi1195R** [comment]
Hi @psrcek,

Can you please share the details requested in our last update? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
