### ISSUE TITLE
Can I set background with image?

### ISSUE THREAD

**Issue by SittiphanSittisak** [syncfusion/flutter-examples#581]
My work needs handwritten in an image like this image below.

![image](https://user-images.githubusercontent.com/59549741/160219667-eb35640b-e6df-4d0c-b2ac-75282d65858e.png)

**Comment by PraveenGopalsamy** [comment]
Hi,

Could you please explain whether you are trying to add a watermark to your sample? If not, kindly explain the use case or reference image (the current image you have provided, we are not clear on what you are trying to achieve) which you are trying to achieve. This will help us to assist you in a better way and provide the solution earlier. Also, we have shared the user guide documentation links to know more about our widget.

UG Link: https://help.syncfusion.com/flutter/signaturepad/getting-started

Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by SittiphanSittisak** [comment]
Hi, thank you for your response.
The image in the first comment has 3 areas for signed.

Now, we can set the color of the background. 
When clicking the button to sign, the app will show the area with the background color that was set like the example below.
![image](https://user-images.githubusercontent.com/59549741/160612065-236a0467-a951-4073-be4e-f06d09cf6f26.png)

After the user signs, the package will generate a file image with auto-crop like this image below.
![image](https://user-images.githubusercontent.com/59549741/160612313-7e62f072-4d6a-488d-be76-c00ffdac1cc0.png)

But my project want to set the image for the background
When clicking the button to sign, the app will show the area with the background image that was set like the example below.
![image](https://user-images.githubusercontent.com/59549741/160612678-f2098605-65a6-4e68-ac56-2463fcca19b0.png)

After the user signs, the package will generate a file image without auto-crop like this image below.
![image](https://user-images.githubusercontent.com/59549741/160612856-e0d48c99-c49e-454c-b240-b7937de20dc1.png)

At this moment, the User needs to sign 3 times.
It would be great If can set the background with an image.

**Comment by PraveenGopalsamy** [comment]
Hi Sittiphan Sittisak,

Thank you for your details. 

We created a sample for achieving your scenario and attached it with this response. You can find the below screenshot for the output from the attached sample. 

**Sample:** [flutter_signaturepad.zip](https://github.com/syncfusion/flutter-examples/files/8379982/flutter_signaturepad.zip)

**Screenshot from the output of the attached sample:**

<img src="https://user-images.githubusercontent.com/83585210/160823286-436da72e-05f8-4c16-bdad-cc8307283fdd.png" width="300">

We hope that this solution will fulfill your requirement. Kindly let us know if you need further assistance with this.

Regards,
Praveen G.

**Comment by SittiphanSittisak** [comment]
Hi, thank you for the best example.
But This error below was shown when I pressed the 'To Image' button.
`
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/scene_builder.dart:94:16
matrix4[0] == window.devicePixelRatio &&
            matrix4[5] == window.devicePixelRatio
is not true
    at Object.throw_ [as throw] (http://localhost:49319/dart_sdk.js:5391:11)
    at Object.assertFailed (http://localhost:49319/dart_sdk.js:5313:15)
    at _engine.SurfaceSceneBuilder.new.pushTransform (http://localhost:49319/dart_sdk.js:178150:133)
    at layer$.OffsetLayer.new.toImage (http://localhost:49319/packages/flutter/src/rendering/layer.dart.lib.js:1505:17)
    at toImage.next (<anonymous>)
    at runBody (http://localhost:49319/dart_sdk.js:43013:34)
    at Object._async [as async] (http://localhost:49319/dart_sdk.js:43044:7)
    at layer$.OffsetLayer.new.toImage (http://localhost:49319/packages/flutter/src/rendering/layer.dart.lib.js:1499:20)
    at proxy_box.RenderRepaintBoundary.new.toImage (http://localhost:49319/packages/flutter/src/rendering/proxy_box.dart.lib.js:3674:26)
    at main._MyHomePageState.new._handleSaveButtonPressed (http://localhost:49319/packages/kt_eclaim/main.dart.lib.js:602:70)
    at _handleSaveButtonPressed.next (<anonymous>)
    at runBody (http://localhost:49319/dart_sdk.js:43013:34)
    at Object._async [as async] (http://localhost:49319/dart_sdk.js:43044:7)
    at main._MyHomePageState.new.[_handleSaveButtonPressed] (http://localhost:49319/packages/kt_eclaim/main.dart.lib.js:599:20)
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:49319/packages/flutter/src/material/icon_button.dart.lib.js:43171:31)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:49319/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:49319/packages/flutter/src/gestures/tap.dart.lib.js:427:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:49319/packages/flutter/src/gestures/tap.dart.lib.js:229:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:49319/packages/flutter/src/gestures/tap.dart.lib.js:175:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:49319/packages/flutter/src/gestures/recognizer.dart.lib.js:454:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:94:9)
    at http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:125:26
    at LinkedMap.new.forEach (http://localhost:49319/dart_sdk.js:29123:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:122:29)
    at pointer_router.PointerRouter.new.route (http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:114:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:394:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:380:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:49319/packages/flutter/src/rendering/layer.dart.lib.js:5808:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:353:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:326:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:315:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:305:65)
    at Object.invoke1 (http://localhost:49319/dart_sdk.js:203779:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:49319/dart_sdk.js:182659:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:49319/dart_sdk.js:183585:49)
    at http://localhost:49319/dart_sdk.js:184068:28
    at http://localhost:49319/dart_sdk.js:184021:16
    at loggedHandler (http://localhost:49319/dart_sdk.js:183695:11)
`

**Comment by SittiphanSittisak** [comment]
This issue is not about this package.
Thank you again for this example.
It's useful.

**Comment by SittiphanSittisak** [comment]
It's a new issue. I will create a new issue.
