### ISSUE TITLE
Cartesian Chart showing errors when trying to show tooltip

### ISSUE THREAD

**Issue by Pipaolo** [syncfusion/flutter-examples#91]
It seems that I am having a strange issue when it comes to showing the tooltip of the Chart, I followed all the steps needed to add tooltips.

```
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  LineSeries<StatsData, String> series;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              RaisedButton(
                child: Text('Fetch Todays Cases'),
                onPressed: () => _fetchTodays(),
              ),
              RaisedButton(
                child: Text('Fetch Yesterdays Cases'),
                onPressed: () {},
              ),
              _buildChart(),
            ],
          ),
        ),
      ),
    );
  }

  _buildChart() {
    if (series != null) {
      return CustomChart(series: series);
    } else {
      return Container();
    }
  }

  _fetchTodays() async {
    final Repository repository = Repository();
    final graphedData = await repository.fetchTodays();
    setState(() {
      series = LineSeries<StatsData, String>(
          enableTooltip: true,
          color: Colors.blue,
          dataSource: graphedData.data,
          yValueMapper: (StatsData data, _) => data.value,
          xValueMapper: (StatsData data, _) =>
              DateFormat('MMM dd').format(data.category),
          markerSettings: MarkerSettings(isVisible: true, height: 4, width: 4),
          name: 'Deaths');
    });
  }
}

class CustomChart extends StatelessWidget {
  const CustomChart({
    Key key,
    @required this.series,
  }) : super(key: key);

  final LineSeries<StatsData, String> series;
  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      title: ChartTitle(text: 'Total Data'),
      legend: Legend(isVisible: true, position: LegendPosition.bottom),
      primaryXAxis: CategoryAxis(
        isVisible: true,
      ),
      primaryYAxis: CategoryAxis(
        isVisible: true,
      ),
      tooltipBehavior: TooltipBehavior(
        enable: true,
    
      ),
      series: <ChartSeries>[series],
      borderColor: Colors.black,
    );
  }
}
```
## Here is the Error message
```

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _getLabelValue 
package:syncfusion_flutter_charts/…/utils/helper.dart:1157
#2      _TooltipPainter._calculateCartesianTooltipText 
package:syncfusion_flutter_charts/…/user_interaction/tooltip_painter.dart:301
#3      _TooltipPainter._renderCartesianChartTooltip.<anonymous closure> 
package:syncfusion_flutter_charts/…/user_interaction/tooltip_painter.dart:262
#4      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
...
Event: PointerUpEvent#42d54(position: Offset(315.4, 364.0))
    position: Offset(315.4, 364.0)
Target: RenderPointerListener#55bea relayoutBoundary=up1
    parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=391.4, 0.0<=h<=229.0)
    size: Size(391.4, 229.0)
    behavior: deferToChild
    listeners: down, move, up
════════════════════════════════════════════════════════════════════════════════
```

**Comment by dharanidharandharmasivam** [comment]
Hi @Pipaolo ,

Thanks for using the Syncfusion Flutter chart widget. We have analyzed the provided code snippet and found that you have rendered the y-axis as CategoryAxis. As of now, the y-axis is supported for numeric and logarithmic axis. So, kindly render the y-axis as numeric axis to resolve the reported scenario. Find the code snippet to resolve the issue.

> 
     primaryYAxis: NumericAxis(
        isVisible: true,
      )

Hope this helps.

Thanks,
Dharani.
